FROM jfloff/alpine-python:2.7
LABEL maintainer="boubouh.karim@gmail.com"
RUN apk --update add libxml2-dev libxslt-dev libffi-dev gcc musl-dev libgcc openssl-dev curl
RUN apk add jpeg-dev zlib-dev freetype-dev lcms2-dev openjpeg-dev tiff-dev tk-dev tcl-dev
RUN mkdir vcar
ADD . vcar/
WORKDIR vcar
RUN pip install certifi
RUN pip install -r requirements2.txt
EXPOSE 5000
ENTRYPOINT [ "python", "manage.py" ]