"""empty message

Revision ID: 04e05fe1720a
Revises: 6e65b1d41290
Create Date: 2017-03-23 02:44:04.454000

"""

# revision identifiers, used by Alembic.
revision = '04e05fe1720a'
down_revision = '6e65b1d41290'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platforms', schema=None) as batch_op:
        batch_op.drop_column('mimetype')

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platforms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mimetype', sa.VARCHAR(length=255), nullable=True))

    ### end Alembic commands ###
