"""empty message

Revision ID: 6e65b1d41290
Revises: d7af0dbace89
Create Date: 2017-03-23 00:27:13.475000

"""

# revision identifiers, used by Alembic.
revision = '6e65b1d41290'
down_revision = 'd7af0dbace89'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platforms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mimetype', sa.String(length=255), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platforms', schema=None) as batch_op:
        batch_op.drop_column('mimetype')

    ### end Alembic commands ###
