"""empty message

Revision ID: 9729c30304a3
Revises: d219e078f4f6
Create Date: 2017-10-24 00:51:51.946750

"""

# revision identifiers, used by Alembic.
revision = '9729c30304a3'
down_revision = 'd219e078f4f6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extrasignals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('storage', sa.String(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('platform_id')

    with op.batch_alter_table('signalclasses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=1000), nullable=True))

    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('frequency', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('range', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('unit', sa.String(length=255), nullable=True))

    with op.batch_alter_table('signalsources', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=1000), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signalsources', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_column('unit')
        batch_op.drop_column('type')
        batch_op.drop_column('range')
        batch_op.drop_column('frequency')
        batch_op.drop_column('description')

    with op.batch_alter_table('signalclasses', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('extrasignals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('platform_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(None, 'platforms', ['platform_id'], ['id'])
        batch_op.drop_column('storage')

    # ### end Alembic commands ###
