"""empty message

Revision ID: d219e078f4f6
Revises: 04e05fe1720a
Create Date: 2017-03-23 02:44:21.361000

"""

# revision identifiers, used by Alembic.
revision = 'd219e078f4f6'
down_revision = '04e05fe1720a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platforms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mimetype', sa.SmallInteger(), nullable=True))

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platforms', schema=None) as batch_op:
        batch_op.drop_column('mimetype')

    ### end Alembic commands ###
