"""empty message

Revision ID: d7af0dbace89
Revises: None
Create Date: 2017-03-11 23:57:43.798009

"""

# revision identifiers, used by Alembic.
revision = 'd7af0dbace89'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_foreign_key('fk-datasets', 'datasets', ['dataset_id'], ['id'])

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.drop_column('article_id')

    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('signalsource_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk-sources', 'signalsources', ['signalsource_id'], ['id'])
        batch_op.create_foreign_key('fk-classes', 'signalclasses', ['signalclass_id'], ['id'])

    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('signals', schema=None) as batch_op:
        batch_op.drop_constraint('fk-sources', type_='foreignkey')
        batch_op.drop_constraint('fk-sources', type_='foreignkey')
        batch_op.drop_column('signalsource_id')

    with op.batch_alter_table('datasets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('article_id', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_constraint('fk-datasets', type_='foreignkey')

    ### end Alembic commands ###
